### ISSUE TITLE
got extremely high precision.  

### ISSUE THREAD

**Issue by dengyang17** [vanzytay/YahooQA_Splits#1]
In my model, I got P@1 0.7896 and MRR 0.8699. It's over 15% higher than the result in these two paper. Is this reasonable??

**Comment by vanzytay** [comment]
Hi. Can you provide more details?

That seems really high. Either you have a very good model, or you might have found good hyperparameters. It's hard to tell without having any details. It might also depend on the pretrained word embeddings. 

Also maybe you could check your evaluation code.
